# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flt_geom_ui_v2\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1329, 786)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.project_name = QtWidgets.QLineEdit(self.centralwidget)
        self.project_name.setGeometry(QtCore.QRect(630, 700, 300, 30))
        self.project_name.setObjectName("project_name")
        self.pb_select = QtWidgets.QPushButton(self.centralwidget)
        self.pb_select.setGeometry(QtCore.QRect(1110, 700, 200, 30))
        self.pb_select.setObjectName("pb_select")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 140, 131, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(490, 470, 321, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(690, 340, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(240, 70, 20, 321))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.res_up_right_bottom = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.res_up_right_bottom.setGeometry(QtCore.QRect(1020, 240, 51, 30))
        self.res_up_right_bottom.setDecimals(2)
        self.res_up_right_bottom.setMinimum(-100000.0)
        self.res_up_right_bottom.setMaximum(100000.0)
        self.res_up_right_bottom.setSingleStep(0.0)
        self.res_up_right_bottom.setObjectName("res_up_right_bottom")
        self.res_low_left_bottom = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.res_low_left_bottom.setGeometry(QtCore.QRect(800, 340, 51, 30))
        self.res_low_left_bottom.setDecimals(2)
        self.res_low_left_bottom.setMinimum(-100000.0)
        self.res_low_left_bottom.setMaximum(100000.0)
        self.res_low_left_bottom.setSingleStep(0.0)
        self.res_low_left_bottom.setObjectName("res_low_left_bottom")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(910, 190, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(1130, 190, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(460, 70, 20, 321))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(30, 470, 281, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.res_up_left_top = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.res_up_left_top.setGeometry(QtCore.QRect(800, 190, 51, 30))
        self.res_up_left_top.setDecimals(2)
        self.res_up_left_top.setMinimum(-100000.0)
        self.res_up_left_top.setMaximum(100000.0)
        self.res_up_left_top.setSingleStep(0.0)
        self.res_up_left_top.setObjectName("res_up_left_top")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(910, 340, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.fc_width = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.fc_width.setGeometry(QtCore.QRect(170, 190, 51, 30))
        self.fc_width.setDecimals(2)
        self.fc_width.setMinimum(1.0)
        self.fc_width.setMaximum(50.0)
        self.fc_width.setObjectName("fc_width")
        self.fc_lense_length = QtWidgets.QSpinBox(self.centralwidget)
        self.fc_lense_length.setGeometry(QtCore.QRect(390, 140, 50, 30))
        self.fc_lense_length.setMinimum(1)
        self.fc_lense_length.setMaximum(100)
        self.fc_lense_length.setProperty("value", 1)
        self.fc_lense_length.setObjectName("fc_lense_length")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(900, 140, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(30, 300, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(690, 290, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(1100, 70, 20, 321))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.fc_dist_bands = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.fc_dist_bands.setGeometry(QtCore.QRect(170, 300, 51, 30))
        self.fc_dist_bands.setDecimals(2)
        self.fc_dist_bands.setMinimum(1.0)
        self.fc_dist_bands.setMaximum(100.0)
        self.fc_dist_bands.setObjectName("fc_dist_bands")
        self.res_low_right_top = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.res_low_right_top.setGeometry(QtCore.QRect(1020, 290, 51, 30))
        self.res_low_right_top.setDecimals(2)
        self.res_low_right_top.setMinimum(-100000.0)
        self.res_low_right_top.setMaximum(100000.0)
        self.res_low_right_top.setSingleStep(0.0)
        self.res_low_right_top.setObjectName("res_low_right_top")
        self.res_low_left_top = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.res_low_left_top.setGeometry(QtCore.QRect(800, 290, 51, 30))
        self.res_low_left_top.setDecimals(2)
        self.res_low_left_top.setMinimum(-100000.0)
        self.res_low_left_top.setMaximum(100000.0)
        self.res_low_left_top.setSingleStep(0.0)
        self.res_low_left_top.setObjectName("res_low_left_top")
        self.res_low_right_bottom = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.res_low_right_bottom.setGeometry(QtCore.QRect(1020, 340, 51, 30))
        self.res_low_right_bottom.setDecimals(2)
        self.res_low_right_bottom.setMinimum(-100000.0)
        self.res_low_right_bottom.setMaximum(100000.0)
        self.res_low_right_bottom.setSingleStep(0.0)
        self.res_low_right_bottom.setObjectName("res_low_right_bottom")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(680, 140, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(650, 70, 20, 321))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pb_innerlense = QtWidgets.QPushButton(self.centralwidget)
        self.pb_innerlense.setGeometry(QtCore.QRect(30, 440, 140, 30))
        self.pb_innerlense.setObjectName("pb_innerlense")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(270, 140, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(270, 190, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.my_extend = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.my_extend.setGeometry(QtCore.QRect(1220, 190, 51, 30))
        self.my_extend.setDecimals(2)
        self.my_extend.setMinimum(0.0)
        self.my_extend.setMaximum(1000000.0)
        self.my_extend.setSingleStep(0.0)
        self.my_extend.setObjectName("my_extend")
        self.sw_numerical = QtWidgets.QStackedWidget(self.centralwidget)
        self.sw_numerical.setGeometry(QtCore.QRect(490, 480, 321, 191))
        self.sw_numerical.setObjectName("sw_numerical")
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.sw_numerical.addWidget(self.page_15)
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setObjectName("page_17")
        self.cbox_numsetup1 = QtWidgets.QCheckBox(self.page_17)
        self.cbox_numsetup1.setGeometry(QtCore.QRect(210, 110, 151, 30))
        self.cbox_numsetup1.setObjectName("cbox_numsetup1")
        self.label_50 = QtWidgets.QLabel(self.page_17)
        self.label_50.setGeometry(QtCore.QRect(20, 10, 191, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.dz_tip_points1 = QtWidgets.QSpinBox(self.page_17)
        self.dz_tip_points1.setGeometry(QtCore.QRect(210, 60, 71, 30))
        self.dz_tip_points1.setMinimum(1)
        self.dz_tip_points1.setMaximum(20)
        self.dz_tip_points1.setProperty("value", 1)
        self.dz_tip_points1.setObjectName("dz_tip_points1")
        self.label_52 = QtWidgets.QLabel(self.page_17)
        self.label_52.setGeometry(QtCore.QRect(20, 60, 191, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.circle_points1 = QtWidgets.QSpinBox(self.page_17)
        self.circle_points1.setGeometry(QtCore.QRect(210, 10, 71, 30))
        self.circle_points1.setMinimum(1)
        self.circle_points1.setMaximum(20)
        self.circle_points1.setProperty("value", 1)
        self.circle_points1.setObjectName("circle_points1")
        self.sw_numerical.addWidget(self.page_17)
        self.fc_dip = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.fc_dip.setGeometry(QtCore.QRect(170, 240, 51, 30))
        self.fc_dip.setDecimals(2)
        self.fc_dip.setMinimum(0.0)
        self.fc_dip.setMaximum(90.0)
        self.fc_dip.setObjectName("fc_dip")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(690, 190, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.m_thickness = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.m_thickness.setGeometry(QtCore.QRect(1220, 240, 51, 30))
        self.m_thickness.setDecimals(2)
        self.m_thickness.setMinimum(0.0)
        self.m_thickness.setMaximum(100.0)
        self.m_thickness.setSingleStep(0.0)
        self.m_thickness.setObjectName("m_thickness")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(1130, 140, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.pb_numerical = QtWidgets.QPushButton(self.centralwidget)
        self.pb_numerical.setGeometry(QtCore.QRect(490, 440, 140, 30))
        self.pb_numerical.setObjectName("pb_numerical")
        self.mx_extend = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.mx_extend.setGeometry(QtCore.QRect(1220, 140, 51, 30))
        self.mx_extend.setDecimals(2)
        self.mx_extend.setMinimum(0.0)
        self.mx_extend.setMaximum(1000000.0)
        self.mx_extend.setSingleStep(0.0)
        self.mx_extend.setObjectName("mx_extend")
        self.dz_width = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dz_width.setGeometry(QtCore.QRect(580, 140, 51, 30))
        self.dz_width.setDecimals(2)
        self.dz_width.setMinimum(1.0)
        self.dz_width.setMaximum(500.0)
        self.dz_width.setObjectName("dz_width")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(690, 240, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(490, 80, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(490, 140, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(30, 380, 1261, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(870, 120, 20, 271))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 110, 1261, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.res_up_left_bottom = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.res_up_left_bottom.setGeometry(QtCore.QRect(800, 240, 51, 30))
        self.res_up_left_bottom.setDecimals(2)
        self.res_up_left_bottom.setMinimum(-100000.0)
        self.res_up_left_bottom.setMaximum(100000.0)
        self.res_up_left_bottom.setSingleStep(0.0)
        self.res_up_left_bottom.setObjectName("res_up_left_bottom")
        self.fc_lense_width = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.fc_lense_width.setGeometry(QtCore.QRect(390, 190, 51, 30))
        self.fc_lense_width.setDecimals(2)
        self.fc_lense_width.setMinimum(1.0)
        self.fc_lense_width.setMaximum(50.0)
        self.fc_lense_width.setObjectName("fc_lense_width")
        self.fc_length = QtWidgets.QSpinBox(self.centralwidget)
        self.fc_length.setGeometry(QtCore.QRect(170, 140, 50, 30))
        self.fc_length.setMinimum(100)
        self.fc_length.setMaximum(100000)
        self.fc_length.setObjectName("fc_length")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 80, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(910, 290, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(1130, 240, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(30, 240, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 190, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(680, 80, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1130, 80, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.sw_innerlense = QtWidgets.QStackedWidget(self.centralwidget)
        self.sw_innerlense.setGeometry(QtCore.QRect(30, 480, 281, 141))
        self.sw_innerlense.setObjectName("sw_innerlense")
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.sw_innerlense.addWidget(self.page_13)
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.label_22 = QtWidgets.QLabel(self.page_14)
        self.label_22.setGeometry(QtCore.QRect(10, 60, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_14)
        self.label_23.setGeometry(QtCore.QRect(10, 10, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.box_ilense = QtWidgets.QCheckBox(self.page_14)
        self.box_ilense.setGeometry(QtCore.QRect(170, 110, 120, 30))
        self.box_ilense.setObjectName("box_ilense")
        self.inlense_l = QtWidgets.QDoubleSpinBox(self.page_14)
        self.inlense_l.setGeometry(QtCore.QRect(170, 10, 51, 30))
        self.inlense_l.setDecimals(2)
        self.inlense_l.setMinimum(0.0)
        self.inlense_l.setMaximum(100.0)
        self.inlense_l.setObjectName("inlense_l")
        self.inlense_w = QtWidgets.QDoubleSpinBox(self.page_14)
        self.inlense_w.setGeometry(QtCore.QRect(170, 60, 51, 30))
        self.inlense_w.setDecimals(2)
        self.inlense_w.setMinimum(0.0)
        self.inlense_w.setMaximum(50.0)
        self.inlense_w.setProperty("value", 1.0)
        self.inlense_w.setObjectName("inlense_w")
        self.sw_innerlense.addWidget(self.page_14)
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(910, 240, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(270, 80, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.res_up_right_top = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.res_up_right_top.setGeometry(QtCore.QRect(1020, 190, 51, 30))
        self.res_up_right_top.setDecimals(2)
        self.res_up_right_top.setMinimum(-100000.0)
        self.res_up_right_top.setMaximum(100000.0)
        self.res_up_right_top.setSingleStep(0.0)
        self.res_up_right_top.setObjectName("res_up_right_top")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(30, 350, 131, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.numb_bands = QtWidgets.QComboBox(self.centralwidget)
        self.numb_bands.setGeometry(QtCore.QRect(170, 350, 51, 30))
        self.numb_bands.setObjectName("numb_bands")
        self.numb_bands.addItem("")
        self.ans_outwrite = QtWidgets.QCheckBox(self.centralwidget)
        self.ans_outwrite.setGeometry(QtCore.QRect(980, 700, 121, 30))
        self.ans_outwrite.setObjectName("ans_outwrite")
        self.fc_lense_dist = QtWidgets.QSpinBox(self.centralwidget)
        self.fc_lense_dist.setGeometry(QtCore.QRect(390, 240, 50, 30))
        self.fc_lense_dist.setMinimum(1)
        self.fc_lense_dist.setMaximum(10000)
        self.fc_lense_dist.setProperty("value", 1)
        self.fc_lense_dist.setObjectName("fc_lense_dist")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(270, 240, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1329, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.sw_numerical.setCurrentIndex(0)
        self.sw_innerlense.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.fc_length, self.fc_width)
        MainWindow.setTabOrder(self.fc_width, self.fc_dip)
        MainWindow.setTabOrder(self.fc_dip, self.fc_dist_bands)
        MainWindow.setTabOrder(self.fc_dist_bands, self.numb_bands)
        MainWindow.setTabOrder(self.numb_bands, self.fc_lense_length)
        MainWindow.setTabOrder(self.fc_lense_length, self.fc_lense_width)
        MainWindow.setTabOrder(self.fc_lense_width, self.dz_width)
        MainWindow.setTabOrder(self.dz_width, self.res_up_left_top)
        MainWindow.setTabOrder(self.res_up_left_top, self.res_up_left_bottom)
        MainWindow.setTabOrder(self.res_up_left_bottom, self.res_low_left_top)
        MainWindow.setTabOrder(self.res_low_left_top, self.res_low_left_bottom)
        MainWindow.setTabOrder(self.res_low_left_bottom, self.res_up_right_top)
        MainWindow.setTabOrder(self.res_up_right_top, self.res_up_right_bottom)
        MainWindow.setTabOrder(self.res_up_right_bottom, self.res_low_right_top)
        MainWindow.setTabOrder(self.res_low_right_top, self.res_low_right_bottom)
        MainWindow.setTabOrder(self.res_low_right_bottom, self.mx_extend)
        MainWindow.setTabOrder(self.mx_extend, self.my_extend)
        MainWindow.setTabOrder(self.my_extend, self.m_thickness)
        MainWindow.setTabOrder(self.m_thickness, self.pb_innerlense)
        MainWindow.setTabOrder(self.pb_innerlense, self.inlense_l)
        MainWindow.setTabOrder(self.inlense_l, self.inlense_w)
        MainWindow.setTabOrder(self.inlense_w, self.box_ilense)
        MainWindow.setTabOrder(self.box_ilense, self.pb_numerical)
        MainWindow.setTabOrder(self.pb_numerical, self.project_name)
        MainWindow.setTabOrder(self.project_name, self.ans_outwrite)
        MainWindow.setTabOrder(self.ans_outwrite, self.pb_select)
        MainWindow.setTabOrder(self.pb_select, self.circle_points1)
        MainWindow.setTabOrder(self.circle_points1, self.dz_tip_points1)
        MainWindow.setTabOrder(self.dz_tip_points1, self.fc_lense_dist)
        MainWindow.setTabOrder(self.fc_lense_dist, self.cbox_numsetup1)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.project_name.setText(_translate("MainWindow", "project name"))
        self.pb_select.setText(_translate("MainWindow", "create geometry"))
        self.label_12.setText(_translate("MainWindow", "Fault Core length"))
        self.label_45.setText(_translate("MainWindow", "right bottom"))
        self.label_36.setText(_translate("MainWindow", "left top"))
        self.label_27.setText(_translate("MainWindow", "y-extend"))
        self.label_34.setText(_translate("MainWindow", "right bottom"))
        self.label_29.setText(_translate("MainWindow", "lower reservoir"))
        self.label_26.setText(_translate("MainWindow", "Distance bands"))
        self.label_33.setText(_translate("MainWindow", "right top"))
        self.label_32.setText(_translate("MainWindow", "upper reservoir"))
        self.pb_innerlense.setText(_translate("MainWindow", "change inner lense"))
        self.label_15.setText(_translate("MainWindow", "Lense length"))
        self.label_16.setText(_translate("MainWindow", "Lense width"))
        self.cbox_numsetup1.setText(_translate("MainWindow", "confirm change"))
        self.label_50.setText(_translate("MainWindow", "lense circle points"))
        self.label_52.setText(_translate("MainWindow", "damage zone tip points"))
        self.label_30.setText(_translate("MainWindow", "left top"))
        self.label_28.setText(_translate("MainWindow", "x-extend"))
        self.pb_numerical.setText(_translate("MainWindow", "change numerical setup"))
        self.label_31.setText(_translate("MainWindow", "left bottom"))
        self.label_9.setText(_translate("MainWindow", "Damage Zone"))
        self.label_24.setText(_translate("MainWindow", "DZ width"))
        self.label_7.setText(_translate("MainWindow", "Fault Core"))
        self.label_37.setText(_translate("MainWindow", "right top"))
        self.label_25.setText(_translate("MainWindow", "thickness"))
        self.label_14.setText(_translate("MainWindow", "Fault Core dip"))
        self.label_13.setText(_translate("MainWindow", "Fault Core width"))
        self.label_10.setText(_translate("MainWindow", "Reservoir Horizon"))
        self.label_11.setText(_translate("MainWindow", "Model Setup"))
        self.label_22.setText(_translate("MainWindow", "inner lense width"))
        self.label_23.setText(_translate("MainWindow", "inner lense length"))
        self.box_ilense.setText(_translate("MainWindow", "confirm change"))
        self.label_35.setText(_translate("MainWindow", "left bottom"))
        self.label_8.setText(_translate("MainWindow", "Fault Core Lense"))
        self.label_49.setText(_translate("MainWindow", "Number of bands"))
        self.numb_bands.setItemText(0, _translate("MainWindow", "3"))
        self.ans_outwrite.setText(_translate("MainWindow", "Ansys Commands"))
        self.label_17.setText(_translate("MainWindow", "Lense distance"))

